[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = "test"
optimizer = true
optimizer_runs = 10_000

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }